site_name: SmartCLIDE Service Creation Testing Frontend Component
repo_url: https://github.com/eclipse-opensmartclide/smartclide-service-creation-theia

nav:
  - Service Creation Testing Frontend: 'index.md'